"use client";

import { useRouter } from "next/navigation";
import { useAnalysis } from "@/context/analysis-context";
import { StepLayout } from "@/components/wizard/step-layout";
import { StepCard } from "@/components/wizard/step-card";
import { Bot } from "lucide-react";

/**
 * Step 2.1: ChatGPT Response
 * Collects the ChatGPT-generated response for comparison
 */
export default function ChatGPTStep() {
  const router = useRouter();
  const { data, updateLLMResponse } = useAnalysis();

  const handleNext = () => {
    router.push("/analyze/gemini");
  };

  return (
    <StepLayout
      currentStep={2}
      totalSteps={5}
      title="ChatGPT Response"
      subtitle="Enter the response generated by ChatGPT for the same prompt"
    >
      <StepCard
        label="ChatGPT Answer"
        placeholder="Paste the ChatGPT-generated response here..."
        helperText="Copy the response from ChatGPT (GPT-4 or GPT-3.5) when given the same question or prompt."
        value={data.llmResponses.chatgpt}
        onChange={(value) => updateLLMResponse("chatgpt", value)}
        onNext={handleNext}
        icon={<Bot className="w-5 h-5" />}
      />
    </StepLayout>
  );
}
