"use client";

import { useRouter } from "next/navigation";
import { useAnalysis } from "@/context/analysis-context";
import { StepLayout } from "@/components/wizard/step-layout";
import { StepCard } from "@/components/wizard/step-card";
import { Sparkles } from "lucide-react";

/**
 * Step 2.2: Gemini Response
 * Collects the Gemini-generated response for comparison
 */
export default function GeminiStep() {
  const router = useRouter();
  const { data, updateLLMResponse } = useAnalysis();

  const handleNext = () => {
    router.push("/analyze/claude");
  };

  return (
    <StepLayout
      currentStep={3}
      totalSteps={5}
      title="Gemini Response"
      subtitle="Enter the response generated by Google Gemini for the same prompt"
    >
      <StepCard
        label="Gemini Answer"
        placeholder="Paste the Gemini-generated response here..."
        helperText="Copy the response from Google Gemini when given the same question or prompt."
        value={data.llmResponses.gemini}
        onChange={(value) => updateLLMResponse("gemini", value)}
        onNext={handleNext}
        icon={<Sparkles className="w-5 h-5" />}
      />
    </StepLayout>
  );
}
