"use client";

import { useRouter } from "next/navigation";
import { useAnalysis } from "@/context/analysis-context";
import { StepLayout } from "@/components/wizard/step-layout";
import { StepCard } from "@/components/wizard/step-card";
import { Brain } from "lucide-react";
import { useState } from "react";

/**
 * Step 2.3: Claude Response
 * Collects the Claude-generated response and triggers analysis
 */

const API_URL = process.env.NEXT_PUBLIC_API_URL;

export default function ClaudeStep() {
  const router = useRouter();
  const { data, updateLLMResponse, setLoading, setError, setResult } =
    useAnalysis();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleAnalyze = async () => {
    setIsSubmitting(true);
    setLoading(true);
    setError(null);

    try {
      // Prepare the request body according to backend spec
      const requestBody = {
        student: data.studentAnswer,
        llms: [
          data.llmResponses.chatgpt,
          data.llmResponses.gemini,
          data.llmResponses.claude,
        ],
      };

      const response = await fetch(`${API_URL}/analyze`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const result = await response.json();

      // Store the result and navigate to results page
      setResult({
        similarityScore: result.similarity_score ?? result.similarityScore ?? 0,
        classifierProbability:
          result.classifier_probability ?? result.classifierProbability,
        finalScore: result.final_score ?? result.finalScore,
      });

      router.push("/analyze/result");
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "An unexpected error occurred"
      );
      router.push("/analyze/result");
    } finally {
      setIsSubmitting(false);
      setLoading(false);
    }
  };

  return (
    <StepLayout
      currentStep={4}
      totalSteps={5}
      title="Claude Response"
      subtitle="Enter the response generated by Anthropic Claude for the same prompt"
    >
      <StepCard
        label="Claude Answer"
        placeholder="Paste the Claude-generated response here..."
        helperText="Copy the response from Claude when given the same question or prompt. This is the final input before analysis."
        value={data.llmResponses.claude}
        onChange={(value) => updateLLMResponse("claude", value)}
        onNext={handleAnalyze}
        isLastStep
        isLoading={isSubmitting}
        icon={<Brain className="w-5 h-5" />}
      />
    </StepLayout>
  );
}
